services:
  - type: web
    name: lwox-gold-bot
    runtime: python
    plan: free
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install --only-binary=:all: -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
